name: CI/CD Docker Build and Push

on:
  push:
    branches: [ "main" ]  # main 브랜치에 코드가 올라가면 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Docker Hub 로그인 (GitHub Secrets 사용)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.parkumin }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Docker 빌드 및 푸시 수행
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # '내계정/이미지명:태그' 형식으로 저장됩니다.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/age-prediction-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}